/* A curated list of real Purdue majors, spanning all colleges, for the
   directory profile form's Major dropdown. Not a perfectly exhaustive
   list of all 190+ official majors — if someone's program isn't here,
   the form falls back to a free-text "Other" field, so nobody's blocked.
   Feel free to add more any time; it's just a plain array. */

const PURDUE_MAJORS = [
  "Accounting",
  "Actuarial Science",
  "Aeronautical and Astronautical Engineering",
  "Aeronautical Engineering Technology",
  "African American Studies",
  "Agribusiness",
  "Agricultural Communication",
  "Agricultural Economics",
  "Agricultural Education",
  "Agricultural Engineering",
  "Agricultural Systems Management",
  "Agronomy",
  "American Studies",
  "Animal Sciences",
  "Animation and Visual Effects",
  "Anthropology",
  "Art and Design",
  "Artificial Intelligence",
  "Asian Studies",
  "Aviation Management",
  "Biochemistry",
  "Biological Engineering",
  "Biology",
  "Biomedical Engineering",
  "Botany and Plant Pathology",
  "Building Construction Management",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Communication",
  "Computer and Information Technology",
  "Computer Engineering",
  "Computer Graphics Technology",
  "Computer Science",
  "Construction Engineering and Management",
  "Creative Writing",
  "Criminology",
  "Cybersecurity",
  "Dance",
  "Data Science",
  "Dietetics",
  "Earth, Atmospheric, and Planetary Sciences",
  "Economics",
  "Electrical Engineering",
  "Electrical Engineering Technology",
  "Elementary Education",
  "Engineering (First-Year/Undecided)",
  "English",
  "Entomology",
  "Environmental and Ecological Engineering",
  "Environmental Science",
  "Exploratory Studies (Undecided)",
  "Film and Video Studies",
  "Finance",
  "Financial Data Analytics",
  "Food Science",
  "Forestry and Natural Resources",
  "French",
  "German",
  "Health and Human Sciences",
  "History",
  "Horticulture",
  "Hospitality and Tourism Management",
  "Human Development and Family Science",
  "Human-Centered Design and Development",
  "Industrial Engineering",
  "Industrial Engineering Technology",
  "Information Systems",
  "Information Technology",
  "Interior Design",
  "Jewish Studies",
  "Journalism and Media",
  "Kinesiology",
  "Landscape Architecture",
  "Linguistics",
  "Management",
  "Marketing",
  "Materials Engineering",
  "Mathematics",
  "Mechanical Engineering",
  "Mechanical Engineering Technology",
  "Microbiology",
  "Music",
  "Natural Resources and Environmental Science",
  "Nursing",
  "Nutrition Science",
  "Operations Management",
  "Organizational Leadership",
  "Pharmaceutical Sciences (Pre-Pharmacy)",
  "Philosophy",
  "Physics",
  "Political Science",
  "Political Science: Pre-Law",
  "Professional Flight Technology",
  "Psychology",
  "Public Health",
  "Public Relations and Strategic Communication",
  "Religious Studies",
  "Retail Management",
  "Robotics and Mechatronics Engineering Technology",
  "Secondary Education",
  "Selling and Sales Management",
  "Sociology",
  "Spanish",
  "Special Education",
  "Statistics",
  "Supply Chain and Operations Management",
  "Technology Leadership and Innovation",
  "Theatre",
  "Veterinary Technology",
  "Wildlife"
];
